spring:
  application:
    name: quickstart

  
  h2:
    console:
      enabled: true
  
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
    
      h2:
        console:
          enabled: true
          path: /h2-console
      username: sa
      password: 
      
mybatis:
  mapper-locations: 
    - mappers/*.xml